name: Build and Deploy to the Server

on:
  [push]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Gradle custom build
        run: ./gradlew deploy
        working-directory: ./web1

      - name: Good to see you here...
        run: 'echo "Author: Jlexender" >> ./web1/helios-root/deploy.sh'

      - name: Rsync to the server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: ./web1/helios-root/
          remote_path: /home/studs/${{ secrets.USERNAME }}/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          remote_port: ${{ secrets.PORT }}
